import type { Metadata } from 'next'
import './globals.scss'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Command and Mention Input',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      </head>
      <body className={`${inter.className} overflow-x-hidden`}>
        <div className="container bg-zinc-200	w-full min-h-screen flex-col items-center justify-between relative">
          {children}
        </div>
      </body>
    </html >
  )
}
